hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "20260401_scalar_mc_env16_exec4_mb2048_increase_actor_lr"
    logger_backends: ["tensorboard", "wandb"]
  max_epochs: 1000
  max_steps: -1
  only_eval: false
  val_check_interval: 1
  save_interval: 40
  save_eval_video: false
  save_rollout_video: false
  num_execute_steps: 4
  eval_video_base_dir: ${runner.logger.log_path}/video/eval
  rollout_video_base_dir: ${runner.logger.log_path}/video/rollout
  resume_dir: null
  ckpt_path: null

wandb:
  key: "local-fb872608a0ec758c86ab35d24eec1373fe2d9313"
  host: "https://microsoft-research.wandb.io"
  entity: msra_rl
  project: rlinf
  run: ${runner.logger.experiment_name}

algorithm:
  rollout_epoch: 2
  eval_rollout_epoch: 1
  update_epoch: 10
  pre_value_update_epoch: 20
  dsrl_minibatch_size: 2048
  dsrl_replay_buffer_capacity_in_epoch: 1.2
  do_adv_norm: true
  adv_norm_eps: 1.0e-8
  advantage_clip: 3.0
  gamma: 0.99
  gae_lambda: 0.95
  dsrl_ppo_clip: 0.2
  dsrl_max_log_ratio: 20.0
  dsrl_entropy_coef: 0.0

env:
  group_name: EnvGroup
  train:
    env_type: libero
    task_suite_name: libero_10
    total_num_envs: 16
    auto_reset: false
    max_steps_per_rollout_epoch: 512
    max_episode_steps: 512
    use_fixed_reset_state_ids: true
    use_ordered_reset_state_ids: false
    specific_task_id: 0
    use_rel_reward: true
    reward_coef: 5.0
    reset_gripper_open: true
    is_eval: false
    seed: 0
    group_size: 1
    init_params:
      camera_heights: 256
      camera_widths: 256
    video_cfg:
      save_video: true
      info_on_video: true
      video_base_dir: ${runner.logger.log_path}/video/train
  eval:
    env_type: libero
    task_suite_name: libero_10
    total_num_envs: 16
    auto_reset: true
    max_steps_per_rollout_epoch: 512
    max_episode_steps: 512
    use_fixed_reset_state_ids: true
    use_ordered_reset_state_ids: false
    specific_task_id: 0
    use_rel_reward: true
    reward_coef: 5.0
    reset_gripper_open: true
    is_eval: true
    seed: 0
    group_size: 1
    init_params:
      camera_heights: 256
      camera_widths: 256
    video_cfg:
      save_eval_video: false
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: RolloutGroup
  generation_backend: huggingface
  recompute_logprobs: false
  enable_offload: false
  pipeline_stage_num: 1
  model:
    model_path: "/path/to/model/SmolVLA-LIBERO-SFT"
    precision: ${actor.model.precision}

actor:
  group_name: ActorGroup
  training_backend: ddp
  micro_batch_size: 16
  global_batch_size: 128
  seed: 42
  enable_offload: false
  model:
    model_path: "/path/to/model/SmolVLA-LIBERO-SFT"
    model_type: smolvla
    precision: bf16
    is_lora: false
    action_dim: 7
    num_action_chunks: 16
    add_value_head: true
    state_dim: 8
    image_keys: ["image", "image2"]
    main_image_env_key: main_images
    wrist_image_env_key: wrist_images
    dsrl_noise_dim: 1600
    dsrl_hidden_dim: 512
    dsrl_actor_num_layers: 4
    dsrl_value_num_layers: 4
    dsrl_value_head_type: scalar
    dsrl_value_v_min: 0.0
    dsrl_value_v_max: 1.0
    dsrl_value_n_bins: 16
    policy_noise_eps: 1.0e-6
    policy_noise_scale: 1.0
    policy_noise_bias: 0.0
  optim:
    lr: 5.0e-6
    dsrl_actor_lr: 1.0e-4
    dsrl_value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0
  fsdp_config:
    strategy: fsdp
    sharding_strategy: no_shard
    disable: true
    gradient_checkpointing: false
    cpu_offload: false
    offload_pin_memory: false
    reshard_after_forward: true
    enable_gradient_accumulation: true
    forward_prefetch: false
    limit_all_gathers: false
    backward_prefetch: null
    use_orig_params: true
    use_liger_kernel: false
    fsdp_size: -1
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}
    amp:
      enabled: false
      precision: bf16
      use_grad_scaler: false

reward:
  use_reward_model: false

critic:
  use_critic_model: false
